package pojo;
// Generated Jun 16, 2020, 9:35:49 PM by Hibernate Tools 4.3.1

import java.util.Vector;




/**
 * Dangky generated by hbm2java
 */
public class Dangky  implements java.io.Serializable {

    public Dangky(DangkyId id) {
        this.id = id;
    }


     private DangkyId id;
     private Lopmonhoc lopmonhoc;
     private Sinhvien sinhvien;
     private Float diemGk;
     private Float diemCk;
     private Float diemKhac;
     private Float diemTong;

    public Dangky() {
    }

	
    public Dangky(DangkyId id, Lopmonhoc lopmonhoc, Sinhvien sinhvien) {
        this.id = id;
        this.lopmonhoc = lopmonhoc;
        this.sinhvien = sinhvien;
    }
    public Dangky(DangkyId id, Lopmonhoc lopmonhoc, Sinhvien sinhvien, Float diemGk, Float diemCk, Float diemKhac, Float diemTong) {
       this.id = id;
       this.lopmonhoc = lopmonhoc;
       this.sinhvien = sinhvien;
       this.diemGk = diemGk;
       this.diemCk = diemCk;
       this.diemKhac = diemKhac;
       this.diemTong = diemTong;
    }
   
    public DangkyId getId() {
        return this.id;
    }
    
    public void setId(DangkyId id) {
        this.id = id;
    }
    public Lopmonhoc getLopmonhoc() {
        return this.lopmonhoc;
    }
    
    public void setLopmonhoc(Lopmonhoc lopmonhoc) {
        this.lopmonhoc = lopmonhoc;
    }
    public Sinhvien getSinhvien() {
        return this.sinhvien;
    }
    
    public void setSinhvien(Sinhvien sinhvien) {
        this.sinhvien = sinhvien;
    }
    public Float getDiemGk() {
        return this.diemGk;
    }
    
    public void setDiemGk(Float diemGk) {
        this.diemGk = diemGk;
    }
    public Float getDiemCk() {
        return this.diemCk;
    }
    
    public void setDiemCk(Float diemCk) {
        this.diemCk = diemCk;
    }
    public Float getDiemKhac() {
        return this.diemKhac;
    }
    
    public void setDiemKhac(Float diemKhac) {
        this.diemKhac = diemKhac;
    }
    public Float getDiemTong() {
        return this.diemTong;
    }
    
    public void setDiemTong(Float diemTong) {
        this.diemTong = diemTong;
    }

    @Override
    public String toString() {
        return "Dangky{" + "id=" + id + ", lopmonhoc=" + lopmonhoc + ", sinhvien=" + sinhvien + ", diemGk=" + diemGk + ", diemCk=" + diemCk + ", diemKhac=" + diemKhac + ", diemTong=" + diemTong + '}';
    }

 public Vector XuatVector()
    {
        Vector vt=new Vector();
        vt.add(this.getId().getMssv());
        vt.add(this.getId().getMaMon());
        vt.add(this.getId().getMaLop());
        
        return vt;
    }
public Vector XuatVectorBangDiem()
    {
        Vector vt=new Vector();
        vt.add(this.getId().getMssv());
       vt.add(this.getSinhvien().getHoTen());
       vt.add(this.diemGk);
       vt.add(this.diemCk);
       vt.add(this.diemKhac);
       vt.add(this.diemTong);
       if(diemTong>=5)
        vt.add("Đậu");
       else
        vt.add("Rớt");
       
        return vt;
    }
public Vector XuatVectorBangDiemSinhVien()
    {
    Vector vt=new Vector();
    vt.add(this.getId().getMaMon());
    vt.add(this.getLopmonhoc().getMonhoc().getTenMon());
    vt.add(this.diemGk);
    vt.add(this.diemCk);
    vt.add(this.diemKhac);
    vt.add(this.diemTong);
       
       
        return vt;
    }

}


