package pojo;
// Generated Jun 15, 2020, 2:25:07 PM by Hibernate Tools 4.3.1



/**
 * Diem generated by hbm2java
 */
public class Diem  implements java.io.Serializable {


     private DiemId id;
     private Monhoc monhoc;
     private Sinhvien sinhvien;
     private Float diemGk;
     private Float diemCk;
     private Float diemKhac;
     private Float diemTong;

    public Diem() {
    }

	
    public Diem(DiemId id, Monhoc monhoc, Sinhvien sinhvien) {
        this.id = id;
        this.monhoc = monhoc;
        this.sinhvien = sinhvien;
    }
    public Diem(DiemId id, Monhoc monhoc, Sinhvien sinhvien, Float diemGk, Float diemCk, Float diemKhac, Float diemTong) {
       this.id = id;
       this.monhoc = monhoc;
       this.sinhvien = sinhvien;
       this.diemGk = diemGk;
       this.diemCk = diemCk;
       this.diemKhac = diemKhac;
       this.diemTong = diemTong;
    }
   
    public DiemId getId() {
        return this.id;
    }
    
    public void setId(DiemId id) {
        this.id = id;
    }
    public Monhoc getMonhoc() {
        return this.monhoc;
    }
    
    public void setMonhoc(Monhoc monhoc) {
        this.monhoc = monhoc;
    }
    public Sinhvien getSinhvien() {
        return this.sinhvien;
    }
    
    public void setSinhvien(Sinhvien sinhvien) {
        this.sinhvien = sinhvien;
    }
    public Float getDiemGk() {
        return this.diemGk;
    }
    
    public void setDiemGk(Float diemGk) {
        this.diemGk = diemGk;
    }
    public Float getDiemCk() {
        return this.diemCk;
    }
    
    public void setDiemCk(Float diemCk) {
        this.diemCk = diemCk;
    }
    public Float getDiemKhac() {
        return this.diemKhac;
    }
    
    public void setDiemKhac(Float diemKhac) {
        this.diemKhac = diemKhac;
    }
    public Float getDiemTong() {
        return this.diemTong;
    }
    
    public void setDiemTong(Float diemTong) {
        this.diemTong = diemTong;
    }




}


