package pojo;
// Generated Jun 15, 2020, 2:25:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Lop generated by hbm2java
 */
public class Lop  implements java.io.Serializable {


     private String maLop;
     private String tenLop;
     private Set lopmonhocs = new HashSet(0);
     private Set sinhviens = new HashSet(0);

    public Lop() {
    }

    public Lop(String maLop, String tenLop) {
        this.maLop = maLop;
        this.tenLop = tenLop;
    }

	
    public Lop(String maLop) {
        this.maLop = maLop;
    }
    public Lop(String maLop, String tenLop, Set lopmonhocs, Set sinhviens) {
       this.maLop = maLop;
       this.tenLop = tenLop;
       this.lopmonhocs = lopmonhocs;
       this.sinhviens = sinhviens;
    }
   
    public String getMaLop() {
        return this.maLop;
    }
    
    public void setMaLop(String maLop) {
        this.maLop = maLop;
    }
    public String getTenLop() {
        return this.tenLop;
    }
    
    public void setTenLop(String tenLop) {
        this.tenLop = tenLop;
    }
    public Set getLopmonhocs() {
        return this.lopmonhocs;
    }
    
    public void setLopmonhocs(Set lopmonhocs) {
        this.lopmonhocs = lopmonhocs;
    }
    public Set getSinhviens() {
        return this.sinhviens;
    }
    
    public void setSinhviens(Set sinhviens) {
        this.sinhviens = sinhviens;
    }




}


