package pojo;
// Generated Jun 16, 2020, 9:35:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Lopmonhoc generated by hbm2java
 */
public class Lopmonhoc  implements java.io.Serializable {


     private LopmonhocId id;
     private Lop lop;
     private Monhoc monhoc;
     private Phong phong;
     private Set dangkies = new HashSet(0);
     private Set sinhviens = new HashSet();
     
    public Lopmonhoc() {
    }

	
    public Lopmonhoc(LopmonhocId id, Lop lop, Monhoc monhoc) {
        this.id = id;
        this.lop = lop;
        this.monhoc = monhoc;
    }
    public Lopmonhoc(LopmonhocId id, Lop lop, Monhoc monhoc, Phong phong, Set dangkies) {
       this.id = id;
       this.lop = lop;
       this.monhoc = monhoc;
       this.phong = phong;
       this.dangkies = dangkies;
    }
   
    public LopmonhocId getId() {
        return this.id;
    }
    
    public void setId(LopmonhocId id) {
        this.id = id;
    }
    public Lop getLop() {
        return this.lop;
    }
    
    public void setLop(Lop lop) {
        this.lop = lop;
    }
    public Monhoc getMonhoc() {
        return this.monhoc;
    }
    
    public void setMonhoc(Monhoc monhoc) {
        this.monhoc = monhoc;
    }
    public Phong getPhong() {
        return this.phong;
    }
    
    public void setPhong(Phong phong) {
        this.phong = phong;
    }
    public Set getDangkies() {
        return this.dangkies;
    }
    
    public void setDangkies(Set dangkies) {
        this.dangkies = dangkies;
    }

    public Set getSinhviens() {
        return sinhviens;
    }

    public void setSinhviens(Set sinhviens) {
        this.sinhviens = sinhviens;
    }

    @Override
    public String toString() {
        return "Lopmonhoc{" + "id=" + id + ", lop=" + lop + ", monhoc=" + monhoc + '}';
    }




}


