package pojo;
// Generated Jun 15, 2020, 2:25:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Monhoc generated by hbm2java
 */
public class Monhoc  implements java.io.Serializable {


     private String maMon;
     private String tenMon;
     private Set lopmonhocs = new HashSet(0);
     private Set diems = new HashSet(0);

    public Monhoc() {
    }

    public Monhoc(String maMon, String tenMon) {
        this.maMon = maMon;
        this.tenMon = tenMon;
    }

	
    public Monhoc(String maMon) {
        this.maMon = maMon;
    }
    public Monhoc(String maMon, String tenMon, Set lopmonhocs, Set diems) {
       this.maMon = maMon;
       this.tenMon = tenMon;
       this.lopmonhocs = lopmonhocs;
       this.diems = diems;
    }
   
    public String getMaMon() {
        return this.maMon;
    }
    
    public void setMaMon(String maMon) {
        this.maMon = maMon;
    }
    public String getTenMon() {
        return this.tenMon;
    }
    
    public void setTenMon(String tenMon) {
        this.tenMon = tenMon;
    }
    public Set getLopmonhocs() {
        return this.lopmonhocs;
    }
    
    public void setLopmonhocs(Set lopmonhocs) {
        this.lopmonhocs = lopmonhocs;
    }
    public Set getDiems() {
        return this.diems;
    }
    
    public void setDiems(Set diems) {
        this.diems = diems;
    }




}


