package pojo;
// Generated Jun 16, 2020, 9:35:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Monhoc generated by hbm2java
 */
public class Monhoc  implements java.io.Serializable {


     private String maMon;
     private String tenMon;
     private Set lopmonhocs = new HashSet(0);

    public Monhoc() {
    }

	
    public Monhoc(String maMon) {
        this.maMon = maMon;
    }
    public Monhoc(String maMon, String tenMon) {
       this.maMon = maMon;
       this.tenMon = tenMon;
    }
    
    public Monhoc(String maMon, String tenMon, Set lopmonhocs) {
       this.maMon = maMon;
       this.tenMon = tenMon;
       this.lopmonhocs = lopmonhocs;
    }
   
    public String getMaMon() {
        return this.maMon;
    }
    
    public void setMaMon(String maMon) {
        this.maMon = maMon;
    }
    public String getTenMon() {
        return this.tenMon;
    }
    
    public void setTenMon(String tenMon) {
        this.tenMon = tenMon;
    }
    public Set getLopmonhocs() {
        return this.lopmonhocs;
    }
    
    public void setLopmonhocs(Set lopmonhocs) {
        this.lopmonhocs = lopmonhocs;
    }

    @Override
    public String toString() {
        return "Monhoc{" + "maMon=" + maMon + ", tenMon=" + tenMon + '}';
    }




}


