package pojo;
// Generated Jun 15, 2020, 2:25:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Phong generated by hbm2java
 */
public class Phong  implements java.io.Serializable {


     private String maPhong;
     private String tenPhong;
     private Set lopmonhocs = new HashSet(0);

    public Phong() {
    }

	
    public Phong(String maPhong) {
        this.maPhong = maPhong;
    }
    public Phong(String maPhong, String tenPhong, Set lopmonhocs) {
       this.maPhong = maPhong;
       this.tenPhong = tenPhong;
       this.lopmonhocs = lopmonhocs;
    }
   
    public String getMaPhong() {
        return this.maPhong;
    }
    
    public void setMaPhong(String maPhong) {
        this.maPhong = maPhong;
    }
    public String getTenPhong() {
        return this.tenPhong;
    }
    
    public void setTenPhong(String tenPhong) {
        this.tenPhong = tenPhong;
    }
    public Set getLopmonhocs() {
        return this.lopmonhocs;
    }
    
    public void setLopmonhocs(Set lopmonhocs) {
        this.lopmonhocs = lopmonhocs;
    }




}


