package pojo;
// Generated Jun 16, 2020, 9:35:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import java.util.Vector;

/**
 * Sinhvien generated by hbm2java
 */
public class Sinhvien  implements java.io.Serializable {


     private String mssv;
     private Lop lop;
     private String hoTen;
     private String cmnd;
     private String gioiTinh;
     private Set dangkies = new HashSet(0);
     private Taikhoan taikhoan;
     private Set lopmonhocs = new HashSet(0);

    public Sinhvien() {
    }

	
    public Sinhvien(String mssv) {
        this.mssv = mssv;
    }
    public Sinhvien(String mssv, Lop lop, String hoTen, String cmnd, String gioiTinh, Taikhoan taikhoan) {
       this.mssv = mssv;
       this.lop = lop;
       this.hoTen = hoTen;
       this.cmnd = cmnd;
       this.gioiTinh = gioiTinh;
       this.taikhoan = taikhoan;
    }
    
    public Sinhvien(String mssv, Lop lop, String hoTen, String cmnd, String gioiTinh, Set dangkies, Taikhoan taikhoan) {
       this.mssv = mssv;
       this.lop = lop;
       this.hoTen = hoTen;
       this.cmnd = cmnd;
       this.gioiTinh = gioiTinh;
       this.dangkies = dangkies;
       this.taikhoan = taikhoan;
    }
   
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }
    public Lop getLop() {
        return this.lop;
    }
    
    public void setLop(Lop lop) {
        this.lop = lop;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }
    public String getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public Set getDangkies() {
        return this.dangkies;
    }
    
    public void setDangkies(Set dangkies) {
        this.dangkies = dangkies;
    }
    public Taikhoan getTaikhoan() {
        return this.taikhoan;
    }
    
    public void setTaikhoan(Taikhoan taikhoan) {
        this.taikhoan = taikhoan;
    }

    public Set getLopmonhocs() {
        return lopmonhocs;
    }

    public void setLopmonhocs(Set lopmonhocs) {
        this.lopmonhocs = lopmonhocs;
    }

    @Override
    public String toString() {
        return "Sinhvien{" + "mssv=" + mssv + ", lop=" + lop + ", hoTen=" + hoTen + ", cmnd=" + cmnd + ", gioiTinh=" + gioiTinh + '}';
    }

    public Vector XuatVector()
    {
        Vector vt=new Vector();
        vt.add(this.mssv);
        vt.add(this.hoTen);
        vt.add(cmnd);
        vt.add(gioiTinh);
        vt.add(lop.getMaLop());
        return vt;
    }

}


