package pojo;
// Generated Jun 16, 2020, 9:35:49 PM by Hibernate Tools 4.3.1

import java.util.Vector;




/**
 * Taikhoan generated by hbm2java
 */
public class Taikhoan  implements java.io.Serializable {


     private String tenTaiKhoan;
     private Sinhvien sinhvien;
     private String matKhau;
     private Boolean isAdmin;

    public Taikhoan() {
    }

	
    public Taikhoan(Sinhvien sinhvien) {
        this.sinhvien = sinhvien;
    }
    
    public Taikhoan(String tenTaiKhoan, String matKhau, Boolean isAdmin) {
       this.tenTaiKhoan = tenTaiKhoan;
       this.matKhau = matKhau;
       this.isAdmin = isAdmin;
    }
    
    public Taikhoan(Sinhvien sinhvien, String matKhau, Boolean isAdmin) {
       this.sinhvien = sinhvien;
       this.matKhau = matKhau;
       this.isAdmin = isAdmin;
    }
   
    public String getTenTaiKhoan() {
        return this.tenTaiKhoan;
    }
    
    public void setTenTaiKhoan(String tenTaiKhoan) {
        this.tenTaiKhoan = tenTaiKhoan;
    }
    public Sinhvien getSinhvien() {
        return this.sinhvien;
    }
    
    public void setSinhvien(Sinhvien sinhvien) {
        this.sinhvien = sinhvien;
    }
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }
    public Boolean getIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    public Vector taoVector()
    {
        Vector vt=new Vector();
        vt.add(this.tenTaiKhoan);
        vt.add(this.matKhau);
        return vt;
    }


}


